calabash/calabash-ios-server

- calabash/Classes/FranklyServer/Routes/LPDumpRoute.m
- calabash/Classes/Utils/LPTouchUtils.h
- calabash/Classes/Utils/LPTouchUtils.m
Adds webview support to the dump route. Example output:
https://gist.github.com/krukow/6dec0732db486b548184
> Provide a dump mechanism for webview doms

- .travis.yml
> remove mjk from travis notifications

- calabash-ios-server-tests/LPScrollOperationTest.m
- calabash.xcodeproj/project.pbxproj
- calabash/Classes/FranklyServer/Operations/LPScrollOperation.m
Changes include:
- Modified scrolling behaviour
- Added unit tests to cover the changes
> Modified scrolling behaviour

- LPTestTarget/en.lproj/LaunchScreen.strings
- LPTestTarget/en.lproj/Main.strings
- calabash.xcodeproj/project.pbxproj
Trying to resolve odd Springboard crashes on the simulator.
Crashes appear in Xcode 6.1.1, 6.2 beta 5, Xcode 6.3 beta.  Springboard says it cannot find xib assets.
The dream is that this will also resolve simulator launch problems on Travis.
> Add en Localization for .xibs in LPTestTarget

- calabash.xcodeproj/project.pbxproj
Syncs the calabash-js module to master and removes some file references in the calabash-js directory from the Xcode project.
> Pulled latest changes from calabash-js submodule

- calabash.xcodeproj/project.pbxproj
- calabash/Classes/CocoaAsyncSocket/GCDAsyncSocket.m
- calabash/Classes/FranklyServer/Routes/LPDebugRoute.m
- calabash/Classes/FranklyServer/Routes/LPQueryLogRoute.m
- calabash/Classes/Utils/LPDevice.h
- calabash/Classes/Utils/LPDevice.m
- calabash/Classes/Utils/LPReflectUtils.m
- calabash/Classes/Utils/LPTouchUtils.m
The static analyzer has been complaining for ever about problems.
I decided to do some house keeping and fix the the most obvious problems.
I am a little nervous about the LPQueryLogRoute.
> Fix obvious memory problems reported by static analyzer

- .gitignore
- .travis.yml
- scripts/ci/travis/local-run-as-travis.rb
- scripts/test/run
- scripts/test/run-ios-simulator-smoke-tests.rb
Transferred the jmoody/animated happiness repo to calabash/ios-smoke-test-app
> Replace jmoody/animated-happiness with calabash/ios-smoke-test-app

- scripts/test/xctest.rb
XCTest is sometimes unable to launch the iOS Simulator to run its tests.
This happens locally occasionally and on Travis CI often.
Apple's release notes say, in short, "We know about this problem; just rerun the test."
This is part of my on-going attempts to stabilize our XCTest suite.
> Fixup retries when XCTest cannot launch simulator

- scripts/test/run-ios-simulator-smoke-tests.rb
Changes to the script logging.
> Use 'CalSmoke' text in test scripts

- calabash/Classes/Utils/LPDevice.m
Part of the Calabash 2.0 spec.
> LPDevice: use 'unknown' for unknown form-factors

- XCTest/Tests/Utils/LPDecimalRounderTest.m
- calabash.xcodeproj/project.pbxproj
- calabash/Classes/Utils/LPDecimalRounder.h
- calabash/Classes/Utils/LPDecimalRounder.m
I need to get some more coverage on LPJSONUtils and how rects and hit points are serialized.
To do that, I need some consistent rounding behaviors.
> LPDecimalRounder - a class for rounding floating point numbers

- XCTest/Tests/Utils/LPJSONUtilsTest.m
- calabash/Classes/Utils/LPJSONUtils.m
I wrote these to get a better understand of how we are serializing rects and floats.
This is in the context of trying to test how we serialize view rects.
> Examples for LPJSONUtils serializeRect: and normalizeFloat:

- calabash.xcodeproj/project.pbxproj
- calabash/Classes/FranklyServer/Routes/LPConditionRoute.h
- calabash/Classes/FranklyServer/Routes/LPConditionRoute.m
- calabash/Classes/Utils/LPRepeatingTimerProtocol.h
- scripts/test/run-ios-simulator-smoke-tests.rb
#142 added a memory leak.  Fixed this, converted to ARC, and add LPRepeatingTimerProtocol for pedantic timer handling.
> Fixup memory leak in LPConditionRoute

- calabash.xcodeproj/project.pbxproj
- calabash/Classes/CocoaHttpServer/LPHTTPConnection.m
- calabash/Classes/CocoaHttpServer/LPHTTPResponse.h
- calabash/Classes/CocoaHttpServer/Responses/LPHTTPAsyncFileResponse.h
- calabash/Classes/CocoaHttpServer/Responses/LPHTTPAsyncFileResponse.m
- calabash/Classes/CocoaHttpServer/Responses/LPHTTPDataResponse.h
- calabash/Classes/CocoaHttpServer/Responses/LPHTTPDataResponse.m
- calabash/Classes/CocoaHttpServer/Responses/LPHTTPDynamicFileResponse.h
- calabash/Classes/CocoaHttpServer/Responses/LPHTTPDynamicFileResponse.m
- calabash/Classes/CocoaHttpServer/Responses/LPHTTPFileResponse.h
- calabash/Classes/CocoaHttpServer/Responses/LPHTTPFileResponse.m
- calabash/Classes/CocoaHttpServer/Responses/LPHTTPRedirectResponse.h
- calabash/Classes/CocoaHttpServer/Responses/LPHTTPRedirectResponse.m
We need to update the CocoaHTTPServer sources.
I tried a all-in-one update, but ran into problems.
Trying an incremental approach.
> Update CocoaHTTPServer Responses

- calabash.xcodeproj/project.pbxproj
- calabash/Classes/FranklyServer/Operations/LPOrientationOperation.m
All the other operations are ARC.
> Covert LPOrientationOperation to ARC

- XCTest/Tests/Operations/LPQueryAllOperationTest.m
- calabash.xcodeproj/project.pbxproj
- calabash/Classes/FranklyServer/Operations/LPQueryAllOperation.m
Trying to get a handle on how this class actually works.
> Rename LPQueryAllOperation local variables and add a couple of unit tests

- calabash.xcodeproj/project.pbxproj
- calabash/Classes/CocoaLumberjack/LPFileLogger.h
- calabash/Classes/CocoaLumberjack/LPLog.h
- calabash/Classes/FranklyServer/Operations/LPCollectionViewScrollToItemWithMarkOperation.m
- calabash/Classes/FranklyServer/Operations/LPScrollToRowWithMarkOperation.m
(>_O) New designated initializers are a pain.
> Xcode 7: resolve new warnings

- CONTRIBUTING.md
- README.md
- VERSIONING.md
They existing docs are confusing and missing several steps.
> Docs: better release instructions

- scripts/test/run-ios-simulator-smoke-tests.rb
Travis CI is failing because the scripts were out of step with changes in ios-smoke-test-app.
> Travis: respond to changes in ios-smoke-test-app

- XCTest/Tests/Operations/LPProcessInfoRouteTest.m
- calabash/Classes/FranklyServer/Routes/LPProcessInfoRoute.m
Would like to see the process arguments as well as the environment to help debug setting/passing args to instruments on the CLI.
> Improve the LPProcessInfoRoute

- XCTest/Tests/Routes/LPReflectionRouteTest.m
- calabash.xcodeproj/project.pbxproj
- calabash/Classes/CalabashServer.m
- calabash/Classes/FranklyServer/Routes/LPReflectionRoute.h
- calabash/Classes/FranklyServer/Routes/LPReflectionRoute.m
@sapieneptus Can you have a look?  Useful?
> Reflection route

- calabash/Classes/Frank/LPCalabashFrankRegistrar.m
- calabash/Classes/FranklyServer/LPRecorder.m
- calabash/Classes/FranklyServer/Operations/LPCollectionViewScrollToItemOperation.m
- calabash/Classes/FranklyServer/Operations/LPCollectionViewScrollToItemWithMarkOperation.m
- calabash/Classes/FranklyServer/Operations/LPDatePickerOperation.m
- calabash/Classes/FranklyServer/Operations/LPOrientationOperation.m
- calabash/Classes/FranklyServer/Operations/LPQueryAllOperation.m
- calabash/Classes/FranklyServer/Operations/LPScrollOperation.m
- calabash/Classes/FranklyServer/Operations/LPScrollToRowOperation.m
- calabash/Classes/FranklyServer/Operations/LPScrollToRowWithMarkOperation.m
- calabash/Classes/FranklyServer/Operations/LPSetTextOperation.m
- calabash/Classes/FranklyServer/Operations/LPSliderOperation.m
- calabash/Classes/FranklyServer/Routes/LPAsyncPlaybackRoute.m
- calabash/Classes/FranklyServer/Routes/LPExitRoute.m
- calabash/Classes/FranklyServer/Routes/LPInterpolateRoute.m
- calabash/Classes/FranklyServer/Routes/LPMapRoute.m
- calabash/Classes/FranklyServer/Routes/LPRecordRoute.m
- calabash/Classes/Invoker/LPInvoker.m
- calabash/Classes/JSON/LPCJSONSerializer.m
- calabash/Classes/JSON/LPISO8601DateFormatter.m
- calabash/Classes/Resources/LPResources.m
- calabash/Classes/UISpec/UIScriptASTWith.m
- calabash/Classes/UISpec/UIScriptParser.m
- calabash/Classes/Utils/LPJSONUtils+Introspection.m
- calabash/Classes/Utils/LPJSONUtils.m
- calabash/Classes/Utils/LPPluginLoader.m
- calabash/Classes/Utils/LPReflectUtils.m
- calabash/Classes/WebViewQuery/LPWKWebViewRuntimeLoader.m
Completes: **Replace NSLog calls with LPLogDebug/Info/Warn/Error** #232
> Replace NSLog calls with LPLog* calls

- README.md
- bin/test/xctest.rb
1. Periodic update.
2. Testing new Calabash Jenkins CI.
> README: expand requirements section and add xcpretty details

- LPTestTarget/AppDelegate.m
- cucumber/features/backdoor.feature
- cucumber/features/steps/backdoor.rb
- cucumber/features/steps/shared.rb
- cucumber/features/support/01_launch.rb
- cucumber/features/support/env.rb
* **backdoor method needs to be updated for 0.17 server changes** [#893](https://github.com/calabash/calabash-ios/issues/893)
Demonstrates and tests the new backdoor capabilities.
> Cucumbers for expanded backdoor capabilities

- XCTest/Tests/Routes/LPSuspendAppRouteTest.m
- calabash/Classes/FranklyServer/Routes/LPSuspendAppRoute.m
- cucumber/features/background.feature
- cucumber/features/steps/background.rb
- cucumber/features/steps/shared.rb
I goofed when I first implemented this and did not use the correct keys in the JSON response.
* Use the correct response keys
* GET returns the UIApplicationState
* Cucumbers to test client behavior
> LPSuspendAppRoute returns correct keys in response

- XCTest/Tests/Utils/LPDeviceTest.m
- calabash/Classes/Utils/LPDevice.m
> LPDevice: add missing iPadPro identifier

- bin/ci/jenkins/run.sh
- bin/test/cucumber.rb
- bin/test/test-cloud.rb
- cucumber/config/cucumber.yml
- cucumber/features/support/01_launch.rb
1. The cucumber tests are failing, but I can't easily tell which ones - using Slowhand formatter
2. Submit an XTC job
> Standup Jenkins in MacMini Colo: part 2

- Gemfile
- Gemfile.lock
- bin/ci/jenkins/run.sh
- bin/test/cucumber.rb
* Jenkins builds are unstable #297
> Stabilize jenkins builds

- bin/make/app-cal.sh
- bin/make/app.sh
Xcode 7.2 broke the 'app' and 'app-cal' rules:
1. Use target + project instead of scheme + project
2. Set more variables so that Xcode will put intermediates and products in the right places
3. The build directory path must be absolute or the CoreData cdtool cannot find the data model 
:8ball:
> Update LPTestTarget build scripts for Xcode 7.2

- Makefile
https://github.com/calabash/calabash-codesign/pull/8
> Make: update the cert fingerprint for dylib signing

- .travis.yml
I am trying to reduce the raw number of emails we are getting from Travis.
> Travis: add slack notifications

- LPTestTarget/de.lproj/Main.strings
- calabash.xcodeproj/project.pbxproj
- calabash/de.lproj/InfoPlist.strings
- cucumber/features/german.feature
- cucumber/features/steps/german_steps.rb
- cucumber/features/steps/shared.rb
- cucumber/features/support/01_launch.rb
Demonstrates that launching simulators with different locales and languages works.
**Launch simulator with locale and language** [#367](https://github.com/calabash/run_loop/pull/367)
> Add DE localization to LPTestTarget

- Gemfile.lock
- LPTestTarget/CocoaHTTPServer/WebSocket.m
- Makefile
- bin/make/dylibs.sh
- calabash.xcodeproj/project.pbxproj
- calabash.xcodeproj/xcshareddata/xcschemes/LPTestTarget.xcscheme
- calabash.xcodeproj/xcshareddata/xcschemes/XCTest.xcscheme
- calabash.xcodeproj/xcshareddata/xcschemes/calabash-dylib.xcscheme
- calabash.xcodeproj/xcshareddata/xcschemes/calabash-plugin-for-frank.xcscheme
- calabash.xcodeproj/xcshareddata/xcschemes/calabash.xcscheme
- calabash.xcodeproj/xcshareddata/xcschemes/version.xcscheme
- calabash/Classes/CocoaHttpServer/LPWebSocket.m
- calabash/Classes/Invoker/LPInvoker.m
- cucumber/features/support/01_launch.rb
* Xcode 7.3 touched the project
* Updated code to resolve new Xcode warnings
* Defer to defaults when running cucumber (:host).
> Xcode 7.3 beta 3 compatibility

- cucumber/Gemfile
- cucumber/config/xtc-other-gems
ATTN: @krukow 
https://github.com/xamarinhq/test-cloud-frameworks/issues/177
> Cucumber: bump version to 2.0

- .travis.yml
- bin/test/cucumber.rb
- bin/test/xctest.rb
- calabash/Classes/WebViewQuery/LPWebQuery.m
This aligns web query results with UIView results, the behavior of Calabash Android, and with user's expectations.
> WebQuery: rect x and y should indicate the top-left corner of the element

- Gemfile.lock
- XCTest/Tests/Routes/LPStatusBarRouteTest.m
- calabash.xcodeproj/project.pbxproj
- calabash/Classes/CalabashServer.m
- calabash/Classes/FranklyServer/Routes/LPStatusBarRoute.h
- calabash/Classes/FranklyServer/Routes/LPStatusBarRoute.m
- cucumber/features/status_bar.feature
- cucumber/features/steps/status_bar.rb
- cucumber/xtc-submit-acquaint.rb
Calabash 2.0 and DeviceAgent need information about the status bar to perform
gestures like full screen pans.
```
$ make xct
$ make app-cal
$ cd cucumber
$ bundle update
$ be cucumber -t @status_bar
```
> Server: implement statusBar route

- Gemfile
- Gemfile.lock
- calabash/Classes/Utils/LPDevice.m
- calabash/Classes/Utils/LPTouchUtils.m
- cucumber/Gemfile
- cucumber/config/xtc-other-gems
* Add device models for iPhone 7 and 7+
* Update sampleFactor for non-optimized / non-zoomed apps running on iPhone 6+ form factors
* Update the command line tools for Xcode 8.0
> Update for Xcode 8 GM and iPhone 7/7+

- README.md
- bin/ci/jenkins/run.sh
- bin/ci/jenkins/s3-publish.sh
- bin/ditto.sh
- bin/log.sh
- bin/make/app-cal.sh
- bin/make/app.sh
- bin/make/dylibs.sh
- bin/make/framework.sh
- bin/make/ipa-cal.sh
- bin/make/version.sh
- bin/simctl.sh
- bin/xcode-build-phase/stage-LPTestTarget-products.sh
- bin/xcode.sh
Completes:
* LPServer: make framework fails on Xcode 9 beta 6; path to library has changed [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/20305)
I am not touching the frank target or shell scripts.  That target will be removed.
> Update build scripts for Xcode 9

- bin/ci/jenkins/make-ipa.sh
- bin/make/ipa-cal.sh
LPTestApp jobs are flickering.
> Jenkins: ensure a new ipa is made before pushing Test Cloud job

- .gitignore
- LPTestTarget/Base.lproj/SecondViewController.xib
- LPTestTarget/SecondViewController.m
- bin/xtc.sh
- cucumber/features/dylib_injection.feature
- cucumber/features/steps/dylib_injection.rb
> Test: add dylib injection test

- XCTest/Tests/Invoker/LPInvokerTest.m
- calabash/Classes/Invoker/LPInvoker.m
Re-raise exception in LPInvoker. See more details in #330.
> Re-raise exception in LPInvoker

- calabash/Classes/CalabashServer.m
https://github.com/calabash/calabash-ios/issues/1386
> remove log redirect

- XCTest/Tests/Invoker/LPInvokerTest.m
- XCTest/Tests/Operations/LPScrollOperationTest.m
- bin/test/cucumber.rb
- bin/test/xctest.rb
- calabash.xcodeproj/project.pbxproj
- calabash/Classes/CalabashServer.m
- calabash/Classes/FranklyServer/Operations/LPScrollOperation.m
- calabash/Classes/Invoker/LPInvoker.h
- calabash/Classes/Invoker/LPInvoker.m
- calabash/Classes/LPI.mm
Fixes:
* UITest: Timeout error on iOS Scrolling on local iOS11 device [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/29352)
> LPScrollOperation: scroll with adjustedContentInset when available

- cucumber/features/dylib_injection.feature
- cucumber/features/steps/shared.rb
Reverts calabash/calabash-ios-server#444
> Revert "Fix logic to switch to the second tab"

- Gemfile
- azure-pipelines.yml
- bin/ci/jenkins/appcenter.sh
- bin/make/app-cal.sh
- bin/test/cucumber.rb
- cucumber/features/dylib_injection.feature
- cucumber/features/steps/shared.rb
I configured build pipeline for TestCloudAgent. I added matrix for Mofave-Xcode with properties (IMAGE_POOL and XCODE_Version).
> Added Azure DevOps CI/CD

- XCTest/Tests/Utils/LPDeviceTest.m
- XCTest/Tests/Utils/LPJSONUtilsTest.m
- bin/test/cucumber.rb
- calabash/Classes/Utils/LPDevice.h
- calabash/Classes/Utils/LPDevice.m
Add support for new iPhones (11, 11 Pro and 11 Pro Max), iPad mini 5th Gen and iPad Air 2019
> Add support for new devices

- azure-pipelines.yml
- bin/ci/az-publish.sh
In this PR we have extended `bin/ci/az-publish.sh` to create and upload `{develop|release}.txt` and `{develop|release}.json` files to the Azure blob container.
> Add develop artifacts

- azure-pipelines.yml
- add Xcode 11.1 and Xcode 11.2 to azure-pipeline matrix
> Add Xcode 11.1 and Xcode 11.2 to matrix

- CHANGELOG.md
- README.md
- bin/test/cucumber.rb
- calabash/Classes/Utils/LPDevice.m
This release contains changes from #463 PR.
Also we've updated `bin/test/cucumber.rb` to run tests on iPhone 12 devices
> Release 0.22.1

- calabash/Classes/UISpec/UIScriptASTClassName.m
- calabash/Classes/Utils/LPTouchUtils.m
This PR adds a basic SwiftUI support to calabash server
> Basic SwiftUI support
