calabash/calabash-ios-server

calabash/Classes/Utils/LPInvoker.m
Fixes bad accesses in downstream calls to dealloc on the `NSDictionary` created by `LPJSONUtils jsonsifyView`.
The problem was revealed by integration tests in calabash-ios; test apps were crashing during certain API calls.
=> LPInvoker: bridge invocation result into ARC

calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/Operations/LPDatePickerOperation.m
Possible memory leak in LPDatePickerOperation can be fixed with ARC.
Not for the 0.12.3 release.
=> Use ARC to fix memory leak in date picker operation

scripts/test/xctest.rb
We've been piping to xcodebuild output to `> /dev/null` because travis does not allow the HUGE amount of output xcodebuild generates.
We would like to use xcpretty, but were having problems handling the exit code.  In particular, if there was a compile error, xcpretty would report success.
I believe this change does the right thing and forwards the correct xcodebuild exit code in all cases.
=> Prefer to run cli tests with xcpretty

calabash-ios-server-tests/LPJSONUtilsTest.m, calabash/Classes/Utils/LPJSONUtils.m
The original implementation was, in some cases, trying to insert `nil` values into a dictionary.
@krukow Looking back on the fix, it occurs to me, you might always _want_ a `hit-point` key.
=> Replace dumpView:toDictionary w/ insertHitPointIntoMutableDictionary:

calabash-ios-server-tests/LPScreenshotRouteTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/Routes/LPScreenshotRoute.h, calabash/Classes/FranklyServer/Routes/LPScreenshotRoute.m
Xcode 6.3 brought to my attention that we were incorrectly testing for `UIGraphicsBeginImageContentWithOptions`.
```
if (NULL != UIGraphicsBeginImageContextWithOptions)
```
This check was required for iOS 4 support.  Since we don't support iOS 4, we can safely remove this branch.
* Put the class under test
* Put the class under ARC
* Reformatted
=> Modernize screenshot route

.gitignore, .travis.yml, Makefile, cucumber/Gemfile, cucumber/Gemfile.develop, cucumber/config/cucumber.yml, cucumber/config/xtc-profiles.yml, cucumber/features/screenshot.feature, cucumber/features/step_definitions/common_steps.rb, cucumber/features/support/01_launch.rb, cucumber/features/support/env.rb, scripts/make-libraries.rb, scripts/test-helpers.rb, scripts/test/cucumber.rb, scripts/test/run-chou-tests.rb, scripts/test/test-make-rules.rb
Looking for a way of pushing integration tests out of XCTest.
Not sure if this approach has legs yet.
If this causes problems in Travis, I will remove the cucumber job. 
Otherwise, this pull-request no effect on the system and can be safely merged.
**UPDATE** Cucumber + dylib injection not stable enough yet for travis.  Remove cucumber.rb from travis build.
=> Add cucumber integration tests

XCTest/LPInfoPlistTest.m, XCTest/LPVersionRouteTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/CalabashServer.m, calabash/Classes/FranklyServer/Routes/LPVersionRoute.m, calabash/Classes/Utils/LPInfoPlist.h, calabash/Classes/Utils/LPInfoPlist.m
This is a combination three of the behaviors.   I decided to keep them together because they all required changes to how we interact with the Info.plist.
* Put LPVersionRoute under ARC - part of an on-going effort to put the entire server under ARC.
* CalabashServer now reports the base SDK of the app under test.
* The version route also reports the base SDK of the app under test.
* The version route now reports "CFBundleVersion" vs. "CFBundleShortVersionString", which is sometimes empty.
```
App Base SDK: iphonesimulator8.3
```
=> LPVersionRoute converted to ARC, safer fetching of values from Info.plist, and CalabashServer logs the App's Base SDK

calabash.xcodeproj/project.pbxproj, calabash/Classes/Utils/LPInvoker.m, calabash/Classes/Utils/LPJSONUtils.m
There was a small memory leak in LPInvoker.
```
$ be briar install calabash-server
$ sim-prepare.sh
$ export APP=/Users/moody/git/briar-ios-example/Briar/Briar-cal.app
$ export TRACE_TEMPLATE="${PWD}/Leaks-Automation.tracetemplate"
$ be cucumber -t @date_picker
```
```
$ cd calabash-ios-server
$ git co develop
```
===
```
$ cd calabash-ios-server
$ git co feature/fix-invoker-memory-leak
```
===
=> Fix LPInvoker memory leak

XCTest/LPLegacyAppRectTranslatorTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/Utils/LPJSONUtils.m, calabash/Classes/Utils/LPLegacyAppRectTranslator.h, calabash/Classes/Utils/LPLegacyAppRectTranslator.m
Checks for _legacy apps running in iOS 8 environments_ and assumes the responsibility of the translating the touch coordinates. 
Historically, the `Calabash::Cucumber::InstrumentsActions::normalize_rect_for_orientation!` method did this work.  Starting in 0.11.0, the server performs the normalization when the test device is iOS 8.
This patch will allow legacy apps to use the most recent version of the calabash gem (0.13.0).
A _legacy app_ has a base SDK of iOS 6.*.
@anujb @jescriba @rasmuskl @TobiasRoikjer @krukow @john7doe @acroos
=> Maintenance patch for translating rects for legacy apps running in iOS 8 environments

calabash/Classes/WebViewQuery/LPWebQuery.m
Skip dom nodes without Rect property. Occurs e.g. with the document / root node
=> Handle case where DOCUMENT_NODE has empty rect

XCTest/Tests/Utils/LPJSONUtilsTest.m, calabash/Classes/Utils/LPJSONUtils.m, calabash/Classes/Utils/LPTouchUtils.m
We observed JSON parse errors for (admittedly strange) views that had a frame with `x` or `y` equal to `inf` or `-inf`.
Particularly we observed an app with a view that serialized as invalid JSON:
```
{"id":null,"description":"<UIButtonLabel: 0x127f05b30; frame = (inf 0; 0 0); hidden = YES; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x17009d470>>",
"label":null,"frame":{"y":0,"x":inf,"width":0,"height":0},
"accessibilityElement":0,"value":null,"alpha":1,"enabled":true,"visible":0,"text":null,"class":"UIButtonLabel",
"rect":{"y":-inf,"height":inf,"center_y":0,"x":-inf,"center_x":0,"width":inf}}],"outcome":"SUCCESS"}
```
=> Fix case where a coordinate is inf or nan

calabash/Classes/FranklyServer/Routes/LPConditionRoute.m, calabash/Classes/FranklyServer/Routes/LPUIATapRoute.m
There was a path through the condition route which would write an http chunk twice leading to an invalid HTTP message (causing the client parser to throw an exception).
This should be fixed with this PR.
=> Fix fall-through causing double write of http chunk

calabash/Classes/FranklyServer/Operations/LPScrollOperation.m, calabash/Classes/FranklyServer/Routes/LPDumpRoute.m, calabash/Classes/UISpec/UIScriptASTWith.m
We had several call sites which called `lpIsWebView` unguarded. Since the view hierarchy can contain both DOM elements (dictionaries) as well as accessibility objects this could lead to crashes.
=> Guard calls to lpIsWebView since we also touch non UIView objects

calabash/Classes/Utils/LPInvoker.m
NSNumber is receiving an unrecognized selector isEqualToString:.
This is being thrown when we ask for the accessibilityLabel of a UITextField.
As far as I can tell, we are not directly responsible for calling isEqualToString on the NSNumber instance.
```
NSInvalidArgumentException: -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x7ae719c0
0   CoreFoundation                      0x0768c746 __exceptionPreprocess + 182
1   libobjc.A.dylib                     0x07a31a97 objc_exception_throw + 44
2   CoreFoundation                      0x07694705 -[NSObject(NSObject) doesNotRecognizeSelector:] + 277
3   CoreFoundation                      0x075db287 ___forwarding___ + 1047
4   CoreFoundation                      0x075dae4e _CF_forwarding_prep_0 + 14
5 …
```
=> Try/Catch around LPInvoker invokeSelector:withTarget:

calabash/Classes/FranklyServer/Operations/LPSliderOperation.m
We got a feature request to support UIControlEvents other than UIControlEventValueDidChange for UISlider.
With briar-ios-example.
=> LPSliderOperation should support any UIControlEvent the target slider is registered to receive

XCTest/Tests/Utils/LPJSONUtilsTest.m, XCTest/Tests/Utils/LPJSONUtils_AccessibilityElementTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/Utils/LPInvoker.m, calabash/Classes/Utils/LPJSONUtils.m
Tightens up the `jsonifyAccessibilityElement:` method.
=> More guards in [LPJSONUtils jsonifyAccessibilityElement:] against unrecognized selectors

scripts/make-calabash-dylib.rb, scripts/make-calabash-lib.rb, scripts/make-frank-lib.rb, scripts/make-lp-test-app.rb
Recently, we had a file that should have been under ARC, but was missing a flag.  A warning was generated, but uncaught during command-line builds.
=> Set GCC_TREAT_WARNINGS_AS_ERRORS=YES for command-line builds

calabash/Classes/CalabashServer.h, calabash/Classes/CalabashServer.m
`LPHTTPServer.h` was included in `CalabashServer.h` even though it is not public. This caused a compilation error when including `CalabashServer.h` from the framework.
Tested using `make framework`.
=> Don't include non-public LPHTTPServer.h in CalabashServer.h

LPTestTarget/AppDelegate.h, LPTestTarget/AppDelegate.m, LPTestTarget/LPCoreDataStack.h, LPTestTarget/LPCoreDataStack.m, LPTestTarget/LPServerEntity.h, LPTestTarget/LPServerEntity.m, LPTestTarget/LPTestTarget.xcdatamodeld/XCTest.xcdatamodel/contents, XCTest/Tests/JSON/LPCJSONSerializerTest.m, calabash.xcodeproj/project.pbxproj, calabash.xcodeproj/xcshareddata/xcschemes/XCTest.xcscheme, calabash/Classes/JSON/LPCJSONSerializer.h, calabash/Classes/JSON/LPCJSONSerializer.m, calabash/Classes/Utils/LPJSONUtils.m
I was interacting with the Keychain API the other day and discovered an error on the server when trying to encode (to JSON) the output of one of the public Keychain API calls.  The result was a RuntimeError in the client.
The public Keychain API method returned an NSDictionary and one of the elements in that array was not a valid JSON object.
The error is occuring because of the the way `LPJSONUtils` is interacting with the LPJSONSerializer.
This was the common pattern:
```objective-c
LPCJSONSerializer *s = [LPCJSONSerializer serializer];
NSError *error = nil;
NSData *d = [s serializeObject:obj error:&error];
if (error) {
NSLog(@"Unable to serialize object (%@), %@", error, [obj description]);
}
NSString *res = [[NSString alloc] initWithBytes:[d bytes] length:[d length] …
```
=> LPJSONSerializer can encode arbitrary objects

calabash/Classes/FranklyServer/Operations/LPDatePickerOperation.m
Avoid the `performSelector:` dance and use the public UIControl API to send actions to the date picker.
=> Date picker: send actions for all UIControlEvents

calabash/Classes/CalabashServer.m
Add some logging to catch errors resulting from dlopen on the UIAutomation framework.
=> CalabashServer: log dlopen UIAutomation errors

calabash/Classes/JSON/LPCJSONSerializer.h, calabash/Classes/JSON/LPCJSONSerializer.m, calabash/Classes/Utils/LPJSONUtils.m
**LPJSONSerializer can encode arbitrary objects** #165  made an unfortunate change in `LPJSONUtils jsonifyObject:` that in some cases strings to become double quoted in query results.
```
> query('tabBarButton', AL)
[
[0] "\"Buttons\"",
[1] "\"Text\"",
[2] "\"Date\"",
[3] "\"Scrolling Views\"",
[4] "\"Sliders\""
]
```
The original implementation, before #165 looked like this:
```
LPCJSONSerializer *s = [LPCJSONSerializer serializer];
NSError *error = nil;
if (![s serializeObject:object error:&error] || error) {
return [object description];
}
return object;
```
That looked like the wrong behavior to me because we were returning a non-JSON object from the method.  It turns out, this behavior is necessary.  I think it is unsafe, but fixing it is beyond the scope of this PR.
FYI/BTW I would …
=> LPJSONUtils fix double quoting of strings in jsonifyObject:

XCTest/Tests/Routes/LPVersionRouteTest.m, calabash/Classes/FranklyServer/Routes/LPVersionRoute.m, scripts/test/run-ios-simulator-smoke-tests.rb
**add a new key: 'short_version_string' ('CFBundleShortVersionString') in the version route** https://github.com/calabash/calabash-ios/issues/773
=> Version route: add key for CFBundleShortVersionString

calabash/Classes/CalabashServer.m, calabash/Classes/Utils/LPPluginLoader.m
=> Avoid [NSURL fileSystemRepresentation] on iOS 6

calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/Operations/LPOrientationOperation.m, calabash/Classes/FranklyServer/Routes/LPMapRoute.m
~~The LPOrientationOperation requires no views.  LPMapRoute was skipping the call to orientation operation because of this.  I don't know what the downstream effects will be.~~
LPMapRoute needed some formatting love and it was a good candidate for converting to ARC.  In the process of converting to ARC, I realized that some of the methods were _only_ for the Frank plug-in.  I documented this and made the Frank calls much safer.
~~I am curious to see how this be476d0 change will affect the server.~~ It was bad.
+1 for CI and +1 for tests that help you understand the behavior of your software.
The _fix_ was a breaking change.  Now I can see that the behavior that prompted this fix was ultimately caused by a misuse of the server API by the client.
```
;; Bad
map_route('/orientation', …
```
=> LPMapRoute: convert to ARC

calabash.xcodeproj/project.pbxproj
Different targets had different "project level headers".
Chris and I were discussing the difference between public, private, and project headers in the Calabash framework.
At the time, I could not find the reference documentation.
When you define a target, you can implement symbols you want to make public to clients of the target’s product. But to make your product easy to use (and to keep implementation details hidden), you may want to keep many of its symbols inaccessible to clients of your product.
Use these criteria to set the appropriate visibility of a header file:
* **Public:** The interface is finalized and meant to be used by your product’s clients. A public header is included in the product as readable source code without restriction.
* **Private:** The interface isn’t intended …
=> Removes 'project level' headers from targets

XCTest/Tests/Utils/LPDeviceTest.m, XCTest/Tests/Utils/LPJSONUtilsTest.m, XCTest/Tests/Utils/LPPluginLoaderTest.m, XCTest/Tests/WebViewQuery/LPIsWebViewTest.m, XCTest/Tests/WebViewQuery/LPWKWebViewRuntimeLoaderTest.m, XCTest/Tests/WebViewQuery/WKWebView+LPWebViewTest.m, calabash/Classes/Utils/LPDevice.h, calabash/Classes/Utils/LPDevice.m
Back in January, when I started to LPJSONUtils under test, I wrote some quick and dirty tests that only worked on iOS 8 iPhone 5s devices.  The command-line tool only runs the tests against this simulator.
This bad practice continued when I implemented the runtime loading of WKWebView support.
I was more than a little embarrassed when I tried to explain this to @sapieneptus in Aarhus.
There is still a some behavior that I don't understand yet with respect to how the center point of a rect is determined, but this PR moves me one step closer.
Unfortunately, some tests fail when in landscape mode because the center points do not match expectations.
=> XCTests should pass when run against any target simulator or device.

XCTest/Tests/LPiOSVersionInlines.h, XCTest/Tests/LPiOSVersionInlinesTest.m, XCTest/Tests/Utils/LPDeviceTest.m, XCTest/Tests/Utils/LPJSONUtilsTest.m, XCTest/Tests/WebViewQuery/LPIsWebViewTest.m, XCTest/Tests/WebViewQuery/LPWKWebViewRuntimeLoaderTest.m, XCTest/Tests/WebViewQuery/WKWebView+LPWebViewTest.m, XCTest/tests.pch, calabash.xcodeproj/project.pbxproj, calabash/Classes/Utils/LPDevice.h, calabash/Classes/Utils/LPDevice.m
As part of **XCTests should pass when run against any target simulator or device.** #184 I added two methods to LPDevice:
* - (NSString *) iOSVersion
* - (BOOL) lessThanIOS8
I don't want to encourage the use of iOS version comparison in the server.  We do this in one place in `LPUIAUserPrefsChannel` where we must know the iOS version to understand the iOS Simulator environment.
I've replaced the two methods from LPDevice with inline C functions that can do equality and inequality comparisons.
Why do I need this?
The behavior of the server is different iOS versions.  My iOS 9 testing is demonstrating that I need to know the iOS version to write good tests.
=> XCTests need a way to compare iOS versions

calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/Routes/LPDebugRoute.m, calabash/Classes/FranklyServer/Routes/LPMapRoute.m, calabash/Classes/Utils/LPLogger.h, calabash/Classes/Utils/LPLogger.m, calabash/Classes/Utils/LPSharedUIATextField.m, calabash/Classes/Utils/LPUIASharedElementChannel.m
It looks like we will be able to use CocoaLumberjack.  I have a local branch that demonstrates this.  The LPLog class clashes with my strategy for including CocoaLumberjack.
Why do we want CocoaLumberjack in the server?  
* Our current CocoaHttpServer and CocoaAsyncSocket files are wildly out of date - last updated in 2011. Xcode 7 revealed dozens of deprecated calls in these files.  Both of these repos use CocoaLumberjack.  The upgrade path will be easier if we can use CocoaLumberjack.
* CocoaLumberjack is a _fantastic_ logging framework - we could do some very cool things with it.
=> Refactor: rename LPLog => LPLogger

calabash.xcodeproj/project.pbxproj, calabash.xcodeproj/xcshareddata/xcschemes/calabash-dylib.xcscheme, calabash.xcodeproj/xcshareddata/xcschemes/calabash-plugin-for-frank.xcscheme, calabash.xcodeproj/xcshareddata/xcschemes/calabash.xcscheme, scripts/make-calabash-dylib.rb, scripts/make-calabash-lib.rb, scripts/make-frank-lib.rb, scripts/make-libraries.rb
We have been maintaining separate Xcode targets for simulators and devices for all the libraries: calabash, frank-plugin, and dylibs.  This makes adding new files to the project tedious and prone to error.  For example, I found some missing .m files in the frank-device target last week.  It is also a little dangerous now that we are working in a mixed ARC/references counting environment - it is very easy to forget to set a `-fobjc-arc` flag in a file.  Ditto for all other file-based flags.
I anticipate upgrading a lot of files (CocoaHttpServer and CocoaAsyncSocket) for Xcode 7/iOS 9 and I don't want to be required to manage all these targets.
I've been investigating how other Objective-C library projects distribute their binaries and realized that we could maintain one target per library …
=> Single Xcode targets for libraries

Makefile, README.md, scripts/make-libraries.rb
We've not been careful about how we code sign the dylibs for release.
Maintainers _must_ follow the install instructions in the README.md here:
* https://github.com/calabash/calabash-codesign
It is painless.  I promise.
@krukow @sapieneptus @TobiasRoikjer 
```
$ make dylibs
```
=> Add Calabash dylib code signing

calabash/Classes/FranklyServer/Routes/LPConditionRoute.m
This works around the parallax animations for UIAlertViewControllers that
are akways attached to the view, even if no animation is occurring.
=> When checking for no animation, ignore animations with trivially short durations

calabash/Classes/CocoaAsyncSocket/LPGCDAsyncSocket.m, calabash/Classes/CocoaLumberjack/LPLog.h
GCDAsyncSocket logging was disabled and still is disabled.
This PR just updates the macros so they conform to the 2.0 CocoaLumberjack format.
=> Modernize GCDAsyncSocket logging

calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/Routes/LPBackdoorRoute.m
This is the behavior already, but this PR guarantees the behavior.
This is in advance of some server changes (CocoaHTTPServer updates).
This PR has been exhaustively tested by:
https://github.com/calabash/ios-smoke-test-app/blob/master/CalSmokeApp/features/backdoor.feature
1. Converts the LPBackdoor class to ARC.
2. Deprecates the appending of missing ':' to selector names.
3. Improves the details and reason strings that are passed back to the client when selector is unrecognized.
=> Ensure backdoors are called on the main thread

calabash/Classes/FranklyServer/Routes/LPConditionRoute.m
We cannot use an NSTimer if we adopt the new CocoaHTTPServer sources.
This PR replaces the NSTimer with a dispatch_* timer.
This dispatch_* approach has been tested against the _old_ CocoaHTTPServer sources.
https://github.com/calabash/ios-smoke-test-app/pull/36
=> Refactor the LPConditionRoute

calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/LPRecorder.h, calabash/Classes/FranklyServer/LPRecorder.m, calabash/Classes/FranklyServer/Routes/LPAsyncPlaybackRoute.m, calabash/Classes/FranklyServer/Routes/LPInterpolateRoute.m, calabash/Classes/FranklyServer/Routes/LPKeyboardRoute.m, calabash/Classes/FranklyServer/Routes/LPRecordRoute.m
We use the playback API for rotating the app.
If the LPAsyncPlaybackRoute is not started on the main thread, then the call to the playback API will hang.
Converted to ARC, applied style, applied standards, and made some clarifying code comments.
=> Ensure playback happens on the main thread

calabash/Classes/WebViewQuery/LPWKWebViewRuntimeLoader.m, calabash/Classes/WebViewQuery/UIWebView+LPWebView.m
If the UIWebView and WKWebView evaluate JavaScript methods are not called on the main thread they will not return the correct values and/or they will cause the application to crash.
Tested with: https://github.com/calabash/ios-webview-test-app
=> Ensure JavaScript is evaluated on the main thread 

.gitignore, Makefile, VersionTool/main.m, calabash.xcodeproj/project.pbxproj, scripts/make-version.sh
It is becoming difficult for me to keep track of the provenance of the framework and dylibs that are committed in various repos:
* Briar iOS Example
* Calabash iOS Smoke Test
* Calabash WebView Test
This PR allows the calabash.framework/Resources/version tool to report the git revision details.
```
$ calabash.framework/Resources/version --revision ALL
git@github.com:calabash/calabash-ios-server.git feature/version-tool-can-return-git-revision 0c56b54
```
There are no other options:  ALL is the only one.
@sapieneptus @krukow @TobiasRoikjer
This might be of interest to you.   It is the same information that is output by `server_version`:
```
"git" => {
"revision" => "b9af34a",
"remote_origin" => "git@github.com:calabash/calabash-ios-server.git",
"branch" => …
```
=> Version tool can return git revision

calabash.xcodeproj/project.pbxproj
The dylib target was not calling the git revision before/after scripts which means that the server_version was reporting the wrong provenance information.
=> Dylib target must call the git revision scripts

calabash/Classes/FranklyServer/Operations/LPQueryAllOperation.m
1. Fixes a long standing memory leak.
2. Found three argument encodings that resulted in crashes.
3. Add support for `long double` encoding for return values and arguments
4. Add support for arguments that are CGPoint and CGRect
5. Add logging for exceptional cases
6. Ensure that invocations and performSelector* calls are done on the main thread
Hurray!
@krukow @sapieneptus
=> LPQueryAllOperation needs some TLC

XCTest/Tests/Invoker/LPInvokerThreadingTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/Routes/LPMapRoute.m, calabash/Classes/Invoker/LPInvoker.h, calabash/Classes/Invoker/LPInvoker.m, calabash/Classes/Utils/LPJSONUtils.m
We need to ensure we are setting the arguments of the invocation and invoking on the main thread.
@sapieneptus Can you have a look at the tests in the XCTests/Invoker/LPInvokerThreadingTest.m?  
I want more tests!
I believe that I will eventually implement your suggest class-that-knows-about-thread, but I am still exploring the problem space.
=> LPInvoker can be forced to execute it's invocations on main thread

calabash.xcodeproj/project.pbxproj, calabash/clean-coverage-files.sh
**requiring "Generate Test Coverage Files" and/or "Instrument Program Flow" causes Console spam** [/specta/#167](https://github.com/specta/specta/issues/167)
=> Delete coverage files before compiling XCTest target

calabash/Classes/FranklyServer/Routes/LPConditionRoute.m
Chris discovered a case where the LPConditionRoute was causing a crash.
I have not been able to reproduce with any of my tests.
```
UIKit_UIApplication_EnsureUIThread + 132
UIKit_UIView_get_BackgroundColor + 20
Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_get_BackgroundColor + 88
< snip >
-[Xamarin_Forms_Platform_iOS_VisualElementRenderer_1 backgroundColor] + 64
+[LPTouchUtils isViewTransparent:] + 44
+[LPTouchUtils isViewVisible:] + 1440
-[UIScriptASTClassName addView:toArray:ifMatchesVisibility:] + 80
-[UIScriptASTClassName evalDescWith:result:visibility:] + 152
-[UIScriptASTClassName evalDescWith:result:visibility:] + 452
-[UIScriptASTClassName evalWith:direction:visibility:] + 400
-[UIScriptParser evalWith:] + 492
+[LPOperation performQuery:] + 424
-[LPConditionRoute …
```
=> LPConditionRoute condition checks need to be done on main thread

XCTest/Tests/Operations/LPOperationTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/Operations/LPCollectionViewScrollToItemOperation.m, calabash/Classes/FranklyServer/Operations/LPCollectionViewScrollToItemWithMarkOperation.m, calabash/Classes/FranklyServer/Operations/LPDatePickerOperation.m, calabash/Classes/FranklyServer/Operations/LPFlashOperation.m, calabash/Classes/FranklyServer/Operations/LPOperation.h, calabash/Classes/FranklyServer/Operations/LPOperation.m, calabash/Classes/FranklyServer/Operations/LPOrientationOperation.m, calabash/Classes/FranklyServer/Operations/LPQueryAllOperation.m, calabash/Classes/FranklyServer/Operations/LPQueryOperation.m, calabash/Classes/FranklyServer/Operations/LPScrollOperation.m, calabash/Classes/FranklyServer/Operations/LPScrollToRowOperation.m, calabash/Classes/FranklyServer/Operations/LPScrollToRowWithMarkOperation.m, calabash/Classes/FranklyServer/Operations/LPSetTextOperation.m, calabash/Classes/FranklyServer/Operations/LPSliderOperation.m, calabash/Classes/FranklyServer/Routes/LPMapRoute.m
* Replaced _ ivars with properties.
* Fixed bizarre _view method argument
* performWithTarget:(UIView *) => performWithTarget:(id) because this is method is often called with non-view objects.
* Organized the code.
* Clarifying code comments about when [LPOperation performWithTarget:] is actually called.
Discovered several cases where performWithTarget: will crash the app.  Deferring fixes until later.
=> Modernize LPOperation's interface and implementation

XCTest/Tests/Operations/LPOperationTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/Operations/LPOperation.m
This method is called by `map` when there there is no matching LPOperation.
I was able to produce a bunch of examples that caused crashes.   
* Added a guard to prevent crashes
* Documented the behavior of the method
* Converted file to ARC
* Wrote some examples.
=> Clean up LPOperation performWithTarget:error:

XCTest/Tests/Routes/LPRouterTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/LPRoute.h, calabash/Classes/FranklyServer/LPRouter.h, calabash/Classes/FranklyServer/LPRouter.m, calabash/Classes/FranklyServer/Operations/LPCollectionViewScrollToItemOperation.m, calabash/Classes/FranklyServer/Operations/LPCollectionViewScrollToItemWithMarkOperation.m, calabash/Classes/FranklyServer/Operations/LPDatePickerOperation.m, calabash/Classes/FranklyServer/Operations/LPFlashOperation.m, calabash/Classes/FranklyServer/Operations/LPOperation.m, calabash/Classes/FranklyServer/Operations/LPScrollOperation.m, calabash/Classes/FranklyServer/Operations/LPScrollToRowOperation.m, calabash/Classes/FranklyServer/Operations/LPScrollToRowWithMarkOperation.m, calabash/Classes/FranklyServer/Operations/LPSliderOperation.m, calabash/Classes/Utils/LPJSONUtils.m, calabash/Classes/WebViewQuery/UIWebView+LPWebView.m
The overarching task is to update the CocoaHTTPServer and CocoaAsyncSocket sources.
This forces HTTP responses to be handled on the main thread.
It allows us to remove _some_ of the unnecessary thread checks that I previously added.
The remaining thread checks are in:
1. LPBackdoorRoute - Will be handled in another PR.
2. LPRecorder -  Execution is forced to the main thread here to allow _rotations_ to occur.  This is not a _route_ or and an _operation_.
3. LPInvoker - provides an API for invoking off and on the main thread.
4. LPWKWebViewRuntimeLoader - WKWebView `evaluateJavaScript:` is async and _must_ be performed on the main thread.  We perform an NSInvocation on the main thread.
5. LPConditionRoute - The timer _must not be started on the main thread._  The checks that timer performs …
=> LPRouter forces response handling to main thread

calabash.xcodeproj/project.pbxproj, calabash/Classes/CocoaHttpServer/LPHTTPAuthenticationRequest.h, calabash/Classes/CocoaHttpServer/LPHTTPAuthenticationRequest.m, calabash/Classes/CocoaHttpServer/LPHTTPConnection.h, calabash/Classes/CocoaHttpServer/LPHTTPConnection.m, calabash/Classes/CocoaHttpServer/LPHTTPMessage.h, calabash/Classes/CocoaHttpServer/LPHTTPMessage.m, calabash/Classes/CocoaHttpServer/LPHTTPServer.h, calabash/Classes/CocoaHttpServer/LPHTTPServer.m, calabash/Classes/CocoaHttpServer/LPWebSocket.h, calabash/Classes/CocoaHttpServer/LPWebSocket.m
CocoaHTTPServer sources are out-of-date.
* [XTC Web Views](https://testcloud.xamarin.com/test/170904d9-95ac-48b4-a160-d8d31889a48f/)
```
34 scenarios (34 passed)
133 steps (133 passed)
3m16.836s
```
* [XTC Smoke Test](https://testcloud.xamarin.com/test/f972e655-4b34-4ea5-a835-e484906f9fba/)
```
53 scenarios (53 passed)
219 steps (219 passed)
9m26.592s
```
* Briar
```
120 scenarios (5 pending, 115 passed)
566 steps (5 pending, 561 passed)
35m15.975s
```
@krukow @sapieneptus @rasmuskl @john7doe 
Also adds LPWebSocket (part of CocoaHTTPServer) which might be of interest to @acroos.
=> Update CocoaHTTPServer 2.3

calabash.xcodeproj/project.pbxproj, calabash/Classes/CalabashServer.m, calabash/Classes/CocoaLumberjack/LPASLLogFormatter.h, calabash/Classes/CocoaLumberjack/LPASLLogFormatter.m, calabash/Classes/CocoaLumberjack/LPLogFormatter.m, calabash/Classes/CocoaLumberjack/LPTTYLogFormatter.h, calabash/Classes/CocoaLumberjack/LPTTYLogFormatter.m
ASL is what is logged to the simulator and device logs.  We cannot remove the date, system name, or process information.
```
Jul 20 08:26:20 stern LPTestTarget[18100]: DEBUG CalabashServer:212 | Creating the server: <LPHTTPServer: 0x7fe86b60d0f0>
```
TTY is what is logged to the Xcode console.
```
2015-07-20 08:30:33.703 DEBUG CalabashServer:212 | Creating the server: <LPHTTPServer: 0x170150d80>
```
=> Use different formatters for ASL and TTY logging

calabash/Classes/FranklyServer/Routes/LPBackdoorRoute.m
To be consistent will all other routes, the backdoor route should return SUCCESS with a 'results' key not 'result'.
To be backward compatible, I simply added another key 'results'.
=> Backdoor route should return a 'results' key

XCTest/Tests/Utils/LPDeviceTest.m, calabash/Classes/FranklyServer/Routes/LPVersionRoute.m, calabash/Classes/Utils/LPDevice.h, calabash/Classes/Utils/LPDevice.m
The changes to LPVersionRoute in  #242 were too aggressive.
Caused failures on the client when setting the attributes of Calabash::Device instances.
=> LPVersionRoute needs to be backward compatible

XCTest/Tests/Utils/LPDeviceTest.m, calabash/Classes/CalabashServer.m, calabash/Classes/Utils/LPDevice.h, calabash/Classes/Utils/LPDevice.m
Last week I was doing a debugging session with Villars and we were having trouble verifying the IP address of a device.
```
CalabashServer:223 | Creating the server: <LPHTTPServer: 0x7fd0c37300d0>
CalabashServer:224 | Calabash iOS server version: CALABASH VERSION: 0.16.4
CalabashServer:227 | App Base SDK: iphonesimulator9.0
CalabashServer:245 | Calabash iOS server is listening on: 192.168.178.31 port 37265
```
This will help debugging especially in cases where users are setting a custom port.
=> Server logs IP address at launch

XCTest/Tests/Routes/LPSuspendAppRouteTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/CalabashServer.m, calabash/Classes/FranklyServer/Routes/LPSuspendAppRoute.h, calabash/Classes/FranklyServer/Routes/LPSuspendAppRoute.m
**FORCE PUSH** Thu Oct 15 21:51 CET
Server side fix for **Xcode 7 GM/iOS 9 send_app_to_background is broken** [#836](https://github.com/calabash/calabash-ios/issues/836).
Uses the "suspend" solution described here: **implement send-app-to-background as a server route** #254 and a private call to `LSApplicationWorkspace` _openApplicationWithBundleID:_.
```
> http({:method => :get, :path => 'suspend'}, {:duration => 3.0})
> http({:method => :get, :path => 'suspend'}, {})
```
Tested on simulators and devices.  [XTC Results](https://testcloud.xamarin.com/test/calsmoke-cal_4356ff98-8856-4d20-a162-e6904058b88f/)
=> Add 'suspend' route to suspend and resume app

XCTest/Tests/Invoker/InvokerFactory.h, XCTest/Tests/Invoker/InvokerFactory.m, XCTest/Tests/Invoker/LPInvokerSelectorWithArgumentsTest.m, calabash/Classes/Invoker/LPInvoker.m
Support for **Expand backdoor route to handle arbitrary method signatures** #220
That PR (among other things) allows LPInvoker to handle the "\_\_nil\_\_" token as nil when passed as an argument.   The problem is that the `argument` may or may not be an instance of NSString.  In cases where the `argument` is not an NSString `isEqualToString:` raises an exception.
This PR does a check for NSString and _then_ calls `isEqualToString:` to check for the special "\_\_self\_\_" and "\_\_nil\_\_" tokens.
=> LPInvoker handles __self__ and __nil__ tokens in arguments

calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/Routes/LPQueryLogRoute.m
Completes: **LPQueryLogRoute has iOS 7 deprecated methods with recommended replacements** #229 
There is no client side implementation for this.  I did some smoke testing based on the examples provided by  @jimmc in **Add ability to query the log file and app delegate properties** #13 and the route appears to work.  At least 2 users think it is valuable.
Added an issue on the client: **Implement client for "querylog" route** [#881](https://github.com/calabash/calabash-ios/issues/881)
=> Replace deprecated methods in LPQueryLog route

XCTest/Tests/Routes/LPBackdoorRouteTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/Routes/LPBackdoorRoute.m
**FORCE PUSHED** rebased Tue 20 Oct 15:04
- Modified `LPBackdoorRoute` to be able to handle `args` key which should be an array of args. This allows invocation of methods with multiple params. 
- Modified `LPInvoker` to accept `@"__nil__"` as nil, thereby allowing clients to pass `nil` as a param to a backdoor. 
- Since I _believe_ a void return type is already handled, this should allow for backdoor methods of arbitrary sigs.
=> Expand backdoor route to handle arbitrary method signatures

LPTestTarget/FirstViewController.m, XCTest/Tests/Routes/LPShakeAppRouteTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/CalabashServer.m, calabash/Classes/FranklyServer/Routes/LPShakeAppRoute.h, calabash/Classes/FranklyServer/Routes/LPShakeAppRoute.m, cucumber/features/shake.feature, cucumber/features/steps/alert_steps.rb, cucumber/features/steps/shake_steps.rb
As discussed in https://github.com/calabash/calabash-ios/issues/873
iOS9+ devices have no ability to mimic shake via UIAutomation, I've filed radar://22796974 but no response.
In the meantime here is an implementation to mimic the shake. I've tested on simulator, but not on device yet. I haven't been able to get the tests running on this suite, I assume I'm missing a dependency or something?
This should only be used for iOS9+ devices as `target.shake()` continues to work for iOS 8.4 and below (even in XCode 7.1).
=> Add 'shake' route to mimic shake of device on iOS9+ devices

bin/make/dylibs.sh, bin/make/framework.sh, bin/make/frank-plugin.sh, calabash.xcodeproj/project.pbxproj
By default xcodebuild only generates bitcode during an Archive action.  This PR adds additional build settings to coerce Xcode into generating bitcode for Debug builds.
There previous build settings inside Xcode where inadequate - the only SDK with the `-fembed-bitcode` option was iphoneos 9.0; no other iOS version had the correct flag.
The make rules check for bitcode in the built libraries.  Detecting bitcode in the dylibs is a little strange.  The string "bitcode" does not appear in the dylib load commands, but LLVM does - but only for the arm* libraries.
@sapieneptus I generated the FAT dylib yesterday from this branch.
Many thanks to @hilli for his help simplifying the bash scripts.
=> ARM builds are forced to emit bitcode

cucumber/features/shake.feature
`shake` is causing app crashes on certain Xcode and iOS combinations [#968](https://github.com/calabash/calabash-ios/issues/968)
This should not block a 0.17.1 release.
=> Cucumber: add @shake feature to quarantine

calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/Operations/LPConstants.m
This file does not technically need to be compiled with ARC, but we should mark it as needing ARC.
The issue is that we will forget that this file is _not_ compiled with ARC and then we add a leak without even knowing it.  This has happened more times than I can remember.
=> LPConstants: needs to be compiled with ARC

calabash/Classes/FranklyServer/Operations/LPConstants.h, calabash/Classes/FranklyServer/Operations/LPConstants.m
I am hazy on the details, but I believe this is the correct way to declare extern'd constants.
This is non-blocking.  Feel free to close if you are not convinced or can argue against.
=> LPConstants: prefer NSString *const pattern

calabash.xcodeproj/project.pbxproj
**REBASED** Wed Jan 6 17:55 CET
LPConstants.h should not be in the Project Headers.
We can discuss if it should be in the Public Headers, but think not.
=> Xcode: remove LPConstants.h from Project Headers

Makefile
More than once I have instructed users to run `make xtc` instead of `make xct`.
The xct remains, but is now an alias for xctests.
FYI/BTW, 'make xctest' was my first choice, but this conflicts with
make's behavior:  if a directory with same name as the rule exists
the rule will exit "xctest is up to date".  The XCTests are in a
directory called 'XCTest'.
=> Make: add xctests rule from running XCTest

calabash/Classes/FranklyServer/Operations/LPScrollOperation.m
The CalWebApp has been failing because scrolling stopped working.
I introduced a bug in October 2015 that caused this.
Fixes **Scrolling on UIWebView and WKWebView is not work working in iOS 9** [#980](https://github.com/calabash/calabash-ios/issues/980)
Discovered this by running the static analyzer.
* build scripts should run the static analyzer #320
=> Fix LPScrollOperation for WebView

README.md, bin/xcode-build-phase/lptesttarget-sign-dylibs.sh, calabash.xcodeproj/project.pbxproj
* calabash-ios-server: 0.18.0 release [#94](https://github.com/xamarinhq/test-cloud-frameworks/issues/94)
* LPTestTarget: embedded plug-ins are not signed correctly #323
=> LPTestTarget: reesign embedded dylibs

calabash/Classes/FranklyServer/Routes/LPScreenshotRoute.m
Resolves:
* screenshot does not capture all views; e.g. custom keyboards and OpenGL views [#789](https://github.com/calabash/calabash-ios/issues/789)
* screenshot route should use drawViewHierarchyInRect:afterScreenUpdates: for iOS 7 [#347](https://github.com/calabash/calabash-ios/issues/347)
* iOS - OpenGL views don't show up in screenshots taken locally (device or simulator), but they do in screenshots taken in the cloud [#134](https://github.com/xamarinhq/test-cloud-frameworks/issues/134)
We've known for a while that the screenshot route does not capture OpenGL - @Clancey demonstrated this at the last Xummit (back in April 2014).  We've been reluctant to change the behavior because of the quality of screenshots when UIAlertView and UIActionSheet are showing.  It seems that this problem …
=> Screenshot: use drawViewHierarchy when possible

calabash/Classes/CalabashServer.m
Having a unique instance name  makes automatic Bonjour service discovery possible.
=> Bonjour: create a unique service instance name

LPTestTarget/Base.lproj/SecondViewController.xib, LPTestTarget/SecondViewController.m, calabash/Classes/Utils/LPDevice.m, cucumber/features/sample_factor.feature, cucumber/features/steps/shared.rb
Resolves **Screen coordinates are incorrect when running in Zoomed mode** [#998](https://github.com/calabash/calabash-ios/issues/998)
On iPhone 6* physical devices, there are two display modes: Zoomed and Standard.  You change the display mode in Settings.app > Display & Brightness > Standard | Zoomed > Set.   Zoomed and Standard display modes have different coordinate spaces.  There is no Zoomed mode for iOS Simulators.
Apps that are not optimized for the iPhone 6* screen size also have different coordinate spaces. In order to be optimized for the iPhone 6* screen sizes, apps must have the correct app icons, launch images, and image assets in 3x sizes.  To complicate matters further, physical devices and simulators have different coordinate space for non-optimized apps.  
This PR fixes …
=> Fix touch coordinates for Zoomed display mode and apps that are not optimized for iPhone 6 screen sizes

XCTest/Tests/Utils/LPJSONUtilsTest.m, calabash/Classes/Utils/LPJSONUtils.h, calabash/Classes/Utils/LPJSONUtils.m
Users are reporting problems deserializing `CGFLOAT_MIN/MAX` with some JSON clients.
This new implementation forces a min/max float that is equivalent to `INT32_MIN/MAX`.  I thought I might try `INT16`, but if I recall correctly the bounds of MKMapView are way beyond these values.
ATTN: @GlennWilson @MatisseHack 
Possible fix for **Invalid number error while using the tree command in the REPL** [#742](https://github.com/xamarin/Xamarin.UITest/issues/742)
=> LPJSONUtils: set max and min float to avoid JSON parse errors

calabash/Classes/FranklyServer/Routes/LPVersionRoute.m
I believe this is for Frank support, but there is no reason why there needs to be a separate `version` route for Frank (it was `calabash_version`).
The goal here is to remove the CALABASH_VERSION_PATH from the client.
It is referenced twice in the client:
* https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/bin/frank-calabash#L70
* https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/lib/calabash-cucumber/launcher.rb#L601
The ultimate goal is to reduce the number of lines of code in client so I can implement an XCUITest action model.
=> LPVersionRoute: remove reference to calabash_version

XCTest/Tests/Utils/LPDeviceTest.m, calabash/Classes/CalabashServer.m, calabash/Classes/Utils/LPDevice.h, calabash/Classes/Utils/LPDevice.m, third-party-licenses/WEBDRIVER_AGENT
Use FB WebDriverAgent category on UIDevice.  The previous implementation was sometimes returning the MAC address of the device.
=> LPDevice: fix ip address reporting

XCTest/Tests/Utils/LPDeviceTest.m, calabash/Classes/Utils/LPDevice.m
Model identifiers for:
* iPhone 6se
* iPad Pro 9in
Resolves **add device model for iPhone 6 SE and iPad Pro 9"** #345
=> LPDevice: detecting 6se and iPad Pro 9in

calabash.xcodeproj/project.pbxproj, calabash/Classes/FranklyServer/LPCORSResponse.m
**Some characters in an element's text/label show up as "?"** [UITest #879](https://github.com/xamarin/Xamarin.UITest/issues/879)
Also set the charset to UTF-8.
@jonstoneman I think the only way to test this in UITest is to build a new CalabashBinding.  Chris or I can show you how to generate the binding.
ATTN: @sapieneptus We should check the response header in DeviceAgent.
=> Response: set the content type to application/json

Gemfile.lock, cucumber/config/cucumber.yml, cucumber/features/issue_246_screenshot_embed.feature, cucumber/features/pages/not_pom.rb, cucumber/features/pages/pom.rb, cucumber/features/steps/issue_246_screenshot_steps.rb
Somewhere along the way we lost the Cucumbers for testing screenshots.
Tests fix for **0.19.0: undefined method `embed` in Calabash::Cucumber.map** [#1083](https://github.com/calabash/calabash-ios/issues/1083)
=> Scenarios for testing Cucumber embed

.gitignore, LPTestTarget/Info.plist, bin/xcode-build-phase/increment-build-number.sh, calabash.xcodeproj/project.pbxproj
I want to be able to support this use case:
```
Given I testing against a physical device
And the app I am testing is already installed
When the installed app version is different than the .ipa I have on disk
Then I want Calabash to install the .ipa from disk
```
On iOS Simulators, we do a checksum to determine if an installed .app is stale.  This is not possible on physical devices; the only information about an app we can get is from the Info.plist.  The idea is to ask "Are the versions of the installed app and the app on disk the same?" and reinstall if the answer is, "No.".
=> Increment LPTestTarget CFBundleVersion for every build

XCTest/Tests/Routes/LPScreenshotRouteTest.m, calabash/Classes/FranklyServer/Routes/LPScreenshotRoute.m
Some users are reporting crashes using the Snapshot API for screenshots.
We don't want to stop using the Snapshot API because it supports UIKit _and_ OpenGL views.
=> LPScreenshot: handle exceptions when calling snapshot API

LPTestTarget/FirstViewController.m, calabash/Classes/UISpec/UIScriptASTWith.m, cucumber/features/steps/webview.rb
Completes the removal of special marked handling.  I thought this was fixed in 0.19.0.  It turns out my fix was incomplete and my test was _really_ bad.
* Unable to Query WebView By ID [#949](https://github.com/xamarin/Xamarin.UITest/issues/949)
* Remove special :marked handling from WebView queries #337
* Cannot query UIWebView by accessibilityIdentifier or accessibilityLabel [#735](https://github.com/calabash/calabash-ios/issues/735)
* query ("webView marked:'XXX'") doesn't work [#85](https://github.com/calabash/calabash-ios/issues/)
* Remove the marked: API from WebView queries. #247
* local cucumbers tests passing
* CalWebApp cucumbers passing
I announced this change with 0.19.0, but the fix was incomplete.  I think we are safe with 0.19.1 release.
ATTN: @jescriba @acroos
=> Remove special :marked handling from WebView queries - take 2

calabash/Classes/Utils/LPDevice.m
Related to:
* Fix touch coordinates for Zoomed display mode and apps that are not optimized for iPhone 6 screen sizes #339
Resolves:
> This PR fixes the touch coordinates for all these cases except one: Non-optimized apps in Zoomed display mode on iPhone 6 Plus physical devices.
Tested against the [iPhoneOnlyApp](https://github.com/calabash/ios-iphone-only-app) in these 6 configurations:
1. Target an iPhone 6 simulator
2. Target an iPhone 6 Plus simulator
3. Target an iPhone 6 in Zoomed mode
4. Target an iPhone 6 in Standard mode
5. Target an iPhone 6 Plus in Zoomed mode
6. Target an iPhone 6 Plus in Standard mode
The server must be able to detect two Scenarios:
1. When the device is in Zoomed vs. Standard mode
2. When the application is not optimized for the iPhone 6* screen sizes.
In …
=> LPDevice: fix sampleFactor for legacy apps in zoomed mode on iphone 6+

XCTest/Tests/Routes/LPSetDeviceOrientationRouteTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/CalabashServer.m, calabash/Classes/FranklyServer/Routes/LPSetDeviceOrientationRoute.h, calabash/Classes/FranklyServer/Routes/LPSetDeviceOrientationRoute.m
Xcode 8.0 beta 3 had a problem setting the device orientation on iOS Simulators.
This appears to be corrected in Xcode 8.0 beta 4.
This PR adds `setOrientation` route to the LPServer which can be used to set the UIDeviceOrientation of iOS Simulators.  It's behavior on physical devices is well understood - it appears to work, but the animation not great (on some devices).
I believe this is worth committing to give us another orientation option.  I don't think we should make a client implementation at this time.
```
#
#
#
#
http({:method => :post, :path => 'setOrientation', {:orientation => < orientation > })
```
Filed a radar and forum post.
* 27638336 REGRESSION: Cannot change the orientation of a simulator with XCUITest in Xcode 8.0 beta 3
* [Developer …
=> Server: add set device orientation route

calabash/Classes/FranklyServer/Operations/LPCollectionViewScrollToItemOperation.m, calabash/Classes/FranklyServer/Operations/LPCollectionViewScrollToItemWithMarkOperation.m, calabash/Classes/FranklyServer/Operations/LPScrollToMarkOperation.h, calabash/Classes/FranklyServer/Operations/LPScrollToMarkOperation.m, calabash/Classes/FranklyServer/Operations/LPScrollToRowOperation.m, calabash/Classes/FranklyServer/Operations/LPScrollToRowWithMarkOperation.m
Resolves:
* scroll_to_collection_view_item_with_mark doesn't work for complex collection view [#1162](https://github.com/calabash/calabash-ios/issues/1162)
* LPServer needs to descend to depth N when searching for marks [JIRA](https://jira.xamarin.com/browse/TCFW-605)
Progress on:
* UITest/XDB ScrollTo [JIRA](https://jira.xamarin.com/browse/TCFW-146)
@jonstoneman This is one piece of the puzzle.  A subsequent PR will add the `map scrollToMark` behavior.
The testing story is not great.
The following Scenarios are running locally on the CalSmokeApp but require some synchronization between the LPServer, run-loop, and Calabash iOS gem to work elsewhere.
I shared the calabash.framework with the user who reported the problem and they verified that it fixed their problem.
```
Scenario: …
```
=> Scroll to marked operations should descend to depth N

calabash/Classes/FranklyServer/LPRouter.m
Log POST request raw bodies (as `NSDictionary *`) to increase helpful output in tests. 
CC: @jmoody
=> Log POST requests w/ body

Makefile
The calabash developer certs expired on January 6th.  The `make dylibs` rule needs to be updated with the latest shasum of the calabash-developer.p12.
Related:
* iOS: update expired certs and add 2 devices [#27](https://github.com/calabash/calabash-codesign/pull/27)
=> Update shasum of the cert used to sign the calabash dylibs

Gemfile.lock, bin/ci/jenkins/make-ipa.sh, bin/ci/jenkins/run.sh, bin/test/xctest.rb
Most jobs on Jenkins have migrated to Xcode 8.   This job is not ready to be migrated - there are failing Xcode 8 unit tests. The Xcode 8-based jobs load the Xcode 8 CoreSimulatorService to keep xcodebuild from failing. This job needs to load the Xcode 7 CoreSimulatorService.
The run_loop version in the Gemfile.lock was 2.2.4 which is ancient.  Updated the Gemfile.lock to get the latest run-loop (2.4.1).
I watched CI and saw that XCTests were failing because the Simulator did not boot properly, so I reworked how we manage the CoreSim processes.
I also revived the XCTest retry algorithm.
Related:
* Fixes finding subview in subviewWithMark #379
=> Jenkins: force Xcode 7 CoreSimulatorService to load

calabash/Classes/FranklyServer/Operations/LPScrollToMarkOperation.m
**Motivation**
I noticed failures in using `ScrollTo(Mark)` because `subviewWithMark` would return a `null` value even though a view with the matching mark was found (it just wasn't the _last_ subview so result would be set to null after having a non-null value) resulting in no scrolling being performed.
=> Fixes finding subview in subviewWithMark

bin/ci/jenkins/run.sh, bin/ci/jenkins/s3-publish.sh, bin/ditto.sh, bin/log-functions.sh, bin/make/dylibs.sh
Progress on automatically injecting the LPServer into applications.
Jenkins jobs will generate 3 artifacts:
```
lastSuccessfulBuild/artifact/Products/s3/s3.json
lastSuccessfulBuild/artifact/Products/s3/s3.yml
lastSuccessfulBuild/artifact/Products/s3/s3.txt
```
Clients can connect to those endpoints to find s3 URLs for various LPServer artifacts.
There are 3 "channels":  master, develop, and pull request.
```
http://calabash-ci.macminicolo.net:8080/jobCalabash%20iOS%20Server%20master
http://calabash-ci.macminicolo.net:8080/jobCalabash%20iOS%20Server%20develop
http://calabash-ci.macminicolo.net:8080/jobCalabash%20iOS%20Server%20PR
```
Assuming this pull request passes, a client could use the following to find the dylib URL:
```
$ curl …
```
=> Prepare for Jenkins to stage artifacts to S3

.gitignore, bin/test/cucumber.rb, calabash.xcodeproj/project.pbxproj, calabash/Classes/CalabashServer.m, calabash/Classes/FranklyServer/Routes/LPClearTextRoute.h, calabash/Classes/FranklyServer/Routes/LPClearTextRoute.m, calabash/Classes/Utils/LPMachClock.h, calabash/Classes/Utils/LPMachClock.m, cucumber/config/xtc-profiles.yml, cucumber/features/device_agent_test_app.feature, cucumber/features/steps/device_agent_test_app.rb, cucumber/features/support/01_launch.rb, cucumber/features/support/acquaint.rb, cucumber/features/support/device_agent_test_app.rb, cucumber/features/support/patches/calabash.rb, cucumber/xtc-submit-device-agent-test-app.rb
**Motivation**
Currently clearing text doesn't trigger any of the appropriate delegate methods or NSNotifications - this PR attempts to address that.
**Update**  - I rebased to use the LPRoute approach.
Tested locally using `GET` on the `/clearText` route. Note - now this requires the keyboard to be open _before_ clearing text.
Accounts for possible scenarios:
**UITextField**
Calls `shouldChangeCharactersInRange` (when selecting all and cut) and `shouldClear` (when selecting the 'x' button) on delegate
Fires `UITextFieldTextDidChange` NSNotification
**UITextView**
Calls `shouldChangeTextIn`, `textViewDidChangeSelection`, `textViewDidChange` on delegate
Fires `UITextViewTextDidChange` NSNotification
**UISearchBar**
Calls `shouldChangeTextIn`, `textDidChange` on delegate
no notifications …
=> Route for clearing text that calls delegate methods and posts text changed notifications

bin/test/xctest.rb, calabash/Classes/Utils/LPDevice.m
Progress on:
* The LPServer should work on iPad Pro 10.5" [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/11134)
* Incorrect iPad Pro Screen Dimensions #388
Completes:
* LPServer: add iPad 10.5" and new iPad 12" model identifiers [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/11874)
=> LPDevice: add new iPad models for June 2017

LPTestTarget/AppDelegate.m, Vendor/Fingertips/Fingertips.LICENSE, Vendor/Fingertips/MBFingerTipWindow.h, Vendor/Fingertips/MBFingerTipWindow.m, XCTest/Tests/Utils/LPDeviceTest.m, calabash.xcodeproj/project.pbxproj, calabash/Classes/Utils/LPDevice.h, calabash/Classes/Utils/LPDevice.m, third-party-licenses/Fingertips.LICENSE
Completes:
* LPServer needs to detect apps and correct touch coordinates that are not optimized for iPad Pro 10.5 [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/12641)
Apps that do not contain the correctly sized Launch Images and Icons are displayed in sample mode on iPhone 6 and 6+ form factors.  Apparently, the same is true for the iPad Pro 10.5" form factor.
When applications contain the correct image assets, the LPServer has 2 pixel accuracy on iPad Pro 10.5.  When testing non-optimized apps, the LPServer needs to scale the touch coordinates.
=> Fix iPad Pro 10.5 touch coordinates for non-optimized apps

calabash/Classes/FranklyServer/Routes/LPUserPrefRoute.m
Currently only `standardUserDefaults` is supported, but for those of us who have shared preferences, specifying `suiteName` would be useful.
=> Can specify suiteName when making changes to user preferences endpoint

XCTest/Tests/Utils/LPDeviceTest.m, calabash/Classes/Utils/LPDevice.h, calabash/Classes/Utils/LPDevice.m
Completes:
* LPServer can identify iPhone 8 and 10 models [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/21936) 
Progress on:
* Calabash iOS supports gestures on iPhone 8 and iPhone X [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/21521)
=> LPDevice: add iPhone X, 8, 8+ model numbers

calabash/Classes/Utils/LPDevice.m
=> LPDevice: update iPhone 8, 8+, and 10 model numbers

bin/test/xctest.rb
Completes:
* Jenkins: LPServer XCTest results are not generating xml files [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/24755)
Ultimately the problem is that XCTest is not generating any test output to stdout so xcpretty cannot create a report.  I confirmed the same thing is happening in DeviceAgent.
We will have to rely on the success/failure of the `xcrun xcodebuild test` process.
Updated the Jenkins jobs accordingly.
=> Test: force xcpretty to write build/reports/junit.xml

bin/ci/jenkins/run.sh, bin/ci/jenkins/s3-publish.sh
Completes:
* Jenkins publishes LPServer dylibs to S3 [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/25390)
```
$ bin/ci/jenkins/s3-publish.sh 
Usage: bin/s3-publish {release | adhoc} [--dry-run]
The first argument controls how the SHA in the S3 url is created.
release => s3://ios-lpserver/<SHA> will be the current git SHA
adhoc => s3://ios-lpserver/<SHA> will be the SHA of the dylib
```
=> Jenkins: jobs push calabash artifacts to S3

calabash/Classes/Utils/LPMachClock.m
Add the `_lp` to symbol to avoid duplicate symbol conflicts when linking the calabash.framework.
=> Server: namespace LPMachClock constant

Makefile, bin/ci/jenkins/appcenter.sh, bin/ci/jenkins/s3-publish.sh, bin/make/dylibs.sh
Progress on:
* DeviceAgent.iOS: can push jobs to AppCenter from Jenkins [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/39206)
To complete that ^ pull request, we updated our code signing repository.  We removed some files that our dylib signing script depended on.  This pull request removes that dependency and simplifies the signing portion of the dylib script.
CI will fail until a pull request on Calabash Codesign is merged.
=> Bin: respond to changes in Calabash.keychain

Gemfile, Jenkinsfile, bin/make/ipa-cal.sh, cucumber/Gemfile
Jenkins has been reinstalled and the timestamper plug-in removed.
Calabash iOS will soon be agnostic re: the cucumber version.
run_loop will soon be agnostic re: the json version
=> Update ruby test env and respond to Jenkins reinstall

calabash/Classes/Utils/LPDevice.m
We noticed one issue in the DeviceAgent - device_info[“form_factor”] returns string “iphone11,6”.
**Changes:**
- Added new devices to formFactorMap
- Fixed iPad 9.7" mapping
=> Update device-model mapping

cucumber/features/dylib_injection.feature, cucumber/features/steps/shared.rb
2 scenarios fail on CI randomly:
1) `Scenario: Entitlement Injector has been loaded`
2) `Scenario: Touch small buttons`
Both of them fail about 4-5 times per 10 runs
The main issues with both tests is that they can't get some value by query
I have added request `query(*)` to failing tests to determine what elements are showed on device screen. I have found that test app still shows elements from the first tab after step `I go to the second tab`. So this step doesn't switch tabs sometimes.
The main issue is that test app sometimes is not switched to the second tab randomly.
I have added logic to touch second tab icon until the second tab is shown.
```
while query("view marked: 'Second View'").empty?
touch("UITabBarButton index:1")
end
```
I have run 11 builds in CI and all of them passed …
=> Fix logic to switch to the second tab

azure-pipelines.yml, bin/ci/az-publish.sh
This PR adds new build step to the `azure-pipelines.yml` file. This build step will perform publishing of build artifacts (see exact list of artifacts below) to the [Azure Blob storage](https://ms.portal.azure.com/#%40microsoft.onmicrosoft.com/resource/subscriptions/9e13100f-ca82-4813-b6ea-9c8d72655924/resourceGroups/TestCloud/providers/Microsoft.Storage/storageAccounts/xtcruntimeartifacts/containersList) (Container name: `ios-test-cloud-agent`). Artifacts from build job with macOS Mojave and Xcode 10.2.1 would be published.
List of artifacts:
```
calabash.framework.zip
calabash-dylibs/libCalabashFAT.dylib
calabash-dylibs/libCalabashARM.dylib
calabash-dylibs/libCalabashSim.dylib
calabash-dylibs/Headers.zip
```
=> Publish TestCloudAgent artifacts to blob storage

bin/test/cucumber.rb, cucumber/features/steps/shared.rb
1) Remove retry-workaround for switching to the second tab. It became redundant because the issue was fixed in Xcode 11 beta 5. It looks like passrate with Xcode 11 beta 5 is about 100%
2) Improve logging in `cucumber.rb` script. Use `vso` prefix to report error to the summary and set job as `SucceededWithIssues` in case if some devices fail.
=> Revert Xcode 11 switching tabs workaround

calabash/Classes/Utils/LPDevice.m
iPhone SE 2 was introduced with Xcode 11.5 beta.
We added it to the `formFactorMap`.
=> Add iPhone SE 2 to the formFactorMap

calabash/Classes/FranklyServer/Routes/LPConditionRoute.m
In iOS 14 the text caret animation started to animate inside of the thread which is not expected behaviour for none animation check. This PR skips animation keys with `UITextSelectionViewCaretBlinkAnimation`
=> Ignore text caret animation

calabash/Classes/Utils/LPDevice.m
The following devices were added in this PR:
- iPhone 12 Mini
- iPhone 12
- iPhone 12 Pro
- iPhone 12 Pro Max
- iPad Air 4th Gen WiFi
- iPad Air 4th Gen WiFi + Celular
=> Add new iPhones and iPads
